

DEBUG:root:2023-02-23 18:36 Traceback (most recent call last):
  File "E:\pyCharm\Emp\app.py", line 28, in <module>
    main()
  File "E:\pyCharm\Emp\app.py", line 11, in main
    mike = Recruiter(name='Mike', salary=123, email='asdfgh@gnail.com')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pyCharm\Emp\employee.py", line 16, in __init__
    self.validate()
  File "E:\pyCharm\Emp\employee.py", line 30, in validate
    raise EmailAlreadyExistsException
Emp.employee.EmailAlreadyExistsException

